### ISSUE TITLE
Website link and paper link for the paper

### ISSUE THREAD

**Issue by DevKiHyun** [DmitryRyumin/INTERSPEECH-2023-Papers#14]
Hi, I'm author of 'disentangled representation learning for multilingual speaker recognition'

Here is our official link (dataset link) and paper link

Website link:
'https://mm.kaist.ac.kr/projects/voxceleb1-b/'

Paper link:
'https://arxiv.org/abs/2211.00437'

**Comment by DevKiHyun** [comment]
And the title in the list is not 'draft learning'. Just 'disentangled representation learning for multilingual speaker recognition'
:)

**Comment by DmitryRyumin** [comment]
> Hi, I'm author of 'disentangled representation learning for multilingual speaker recognition'
> 
> Here is our official link (dataset link) and paper link
> 
> Website link: 'https://mm.kaist.ac.kr/projects/voxceleb1-b/'
> 
> Paper link: 'https://arxiv.org/abs/2211.00437'

Hi @DevKiHyun,

Everything has been addressed and updated according to your wishes. Additionally, if you like, you can add a link to the original paper from the conference after the Interspeech conference.

Feel free to contact me if you have any further additions or changes.

Thank you very much!
