### ISSUE TITLE
Questions for contribution. (paper session, branch)

### ISSUE THREAD

**Issue by zlin0** [DmitryRyumin/INTERSPEECH-2023-Papers#6]
@DmitryRyumin Hi, I saw the invitation from you, and this repository is really helpful! May I ask some questions regarding contribution?

1. Is the paper categorized based on [the official session of papers announced by IS2023](https://interspeech2023.org/wp-content/uploads/2023/06/INTERSPEECH_2023_Booklet_v1.pdf)? (If so, may I restructure some incorrectly categorized papers directly?)
2. When submitting updates, should I fork and create a new sub-branch, or can I directly submit to the `main` branch? (I noticed others submit to the main directly, but here to confirm in case.)
3. If there are any other considerations I should pay attention to?

**Comment by DmitryRyumin** [comment]
Hi @zlin0, thank you for your interest in the repository and your willingness to contribute! I appreciate your questions and I'm here to provide some clarification.

1. Yes, the papers in the repository are categorised based on the official paper sessions announced by **Interspeech 2023**. If you come across incorrectly categorised papers, please feel free to restructure them by moving them to the appropriate sections. Your help in improving the categorisation is very valuable.
2. When it comes to submitting updates, you have a number of options. You can make changes directly to the `main` branch, if you feel comfortable doing so. Alternatively, if you prefer, you can `fork` the repository and create a new `sub-branch` to work on your updates. Both approaches are acceptable, and it depends on your personal preference and familiarity with the Git workflow. If you choose to make a `pull request`, it can be a convenient way for us to review your changes before merging them into the `main` branch.
3. As for other considerations, there aren't many specific guidelines to follow. However, let me share the overall vision for this repository. My goal was to create a central repository that would bring together articles from the **Interspeech 2023** conference. The intention is to facilitate collaboration between authors, enthusiasts and experts in the field of speech and language processing. After the conference, I plan to further enhance this repository by adding links to the latest versions of the Interspeech articles. This way, all the valuable information from **Interspeech 2023** will be consolidated in one place.

Thank you again for your interest and willingness to contribute. If you have any further questions or need assistance, please don't hesitate to ask. I'm here to help!
