### ISSUE TITLE
Repositories for paper Automatic Assessment of Oral Reading Accuracy for Reading Diagnostics

### ISSUE THREAD

**Issue by cristiantg** [DmitryRyumin/INTERSPEECH-2023-Papers#7]
Hi, could you please add teh following repositories to the paper: "Automatic Assessment of Oral Reading Accuracy for Reading Diagnostics"?
https://github.com/bomolenaar/jasmin_data_prep
https://github.com/cristiantg/kaldi_egs_CGN/tree/onPonyLand
Thank you,
Cristian.

**Comment by MiSTeR1995** [comment]
Hi! Done ✅ Thanks for repositories!
